---
title: "Host blood meal GLM/Chi-squared"
author: "Kacie Ring"
date: "4/5/2021"
output:
  html_document: default
  pdf_document: default
---

Step 1: Load in data. Set larval blood meal source and infection status as factors 
```{r setup, include = FALSE}

#setwd("~/Desktop/SFSU/Host_Legacy_GLM")
tick<-read.csv("Host_Blood_Meal_Data.csv", header=T)

#install.packages("lme4")
#install.packages("glmm")
#install.packages("magrittr")
library(magrittr)
library(tidyverse)
library(lme4)
library(glmm)
library(ggplot2)
library(GGally)
library(broom)
library(jtools)
library(caret)
library(AICcmodavg)



```


```{r}

#Turn categorical variables into factors 
tick$Infection.Status<-as.factor(tick$Infection.Status)
tick$Larval.Blood.Meal<-as.factor(tick$Larval.Blood.Meal)
tick$Trial <-as.factor(tick$Trial)
tick$HostID <-as.factor(tick$HostID)

str(tick)
```



Step 2: Chi-squared test + bar & mosiac plots 
```{r}
ctable<- table(tick$Larval.Blood.Meal, tick$Infection.Status)
ctable
test <- chisq.test(table(tick$Larval.Blood.Meal, tick$Infection.Status))
test

#create mosaic plot 
mosaicplot(ctable, main = "Infection status of Bb engorged nymphs",
           xlab= "Larval blood meal",
           ylab = "Infection status",
           las = 1,
           color = c("azure4", "darkcyan"))
```


```{r}
#bar plot to view raw experimental results

#Supplemental Figure 1 
ggplot (tick, 
        aes(x = Larval.Blood.Meal, fill = Infection.Status)) + 
        geom_bar(position = "dodge", color = "black") + 
        labs(title = "Infection status of Bb engorged nymphs", x ="Larval host   blooodmeal", y = "Tick count", fill = "Infection status") + 
        theme_bw() + scale_fill_manual(values = c("azure4", "darkcyan")) 
       
```


Step 3: Glmm
```{r}
#Trial and Nymphal (infected) C3H mouse host ID as random effecs 
#Is larval blood meal a significant predictor of Infection status? 


tick_model1<-glmer(Infection.Status~Larval.Blood.Meal+(1|Trial), data=tick, family=binomial(link="logit"))

summary(tick_model1)

unique(tick$HostID)

tick_model2<-glmer(Infection.Status~Larval.Blood.Meal+(1|HostID), data=tick, family=binomial(link="logit"))

summary(tick_model2)

#tick_model3<-glmer(Infection.Status~Larval.Blood.Meal+(1+Larval.Blood.Meal|Trial)+(1+Larval.Blood.Meal|HostID), data=tick, family=binomial(link="logit"))

#summary(tick_model3)

#first attempt
tick_model4<-glmer(Infection.Status~Larval.Blood.Meal+(1|Trial)+(1|HostID), data=tick, family=binomial(link="logit"))

summary(tick_model4)
isSingular(tick_model4)

tick_model5<-glmer(Infection.Status~Larval.Blood.Meal+(1|HostID)+(1|Trial), data=tick, family=binomial(link="logit"))
summary(tick_model5)


#Model above is singular. Are random effects crossed? Let's remodel 

tick_model6<-glmer(Infection.Status~Larval.Blood.Meal+(1|Trial:HostID), data=tick, family=binomial(link="logit"))

summary(tick_model6)

anova(tick_model4)
rand(tick_model4)

#Need to investigate model singularity and "Model failed to converge" error 

isSingular(tick_model5)


#Are trial and Mouse ID independent??? Narrr

```
```{r}
#Let's try and troubleshoot this convergence problem 

nrow(tick)

length(getME(tick_model4,"theta"))

length(fixef(tick_model4))

#Checking for singularity - with estimates 

tt <- getME(tick_model4,"theta")
ll <- getME(tick_model4,"lower")
min(tt[ll==0])

#Okay singularity doesn't seeem to be the issue here 



```


```{r}
#create Figure 2 for RIng et al 2022 manuscript 

#convert bloodmeal to factor (lizard or mouse)
tick$Larval.Blood.Meal<-as.factor(tick$Larval.Blood.Meal)

#load in required packages 
library(magrittr)
library(tidyverse)
library(ggplot2)
library(ragg)

#set qqplot theme 
theme_set(theme_bw()); theme_update(plot.title = element_text(hjust = 0.5))

#subset data into lizard and mouse dataframes 
liz<-subset(tick, Larval.Blood.Meal=="Scoc")
mouse<-subset(tick, Larval.Blood.Meal=="Pema")

Pema<-mouse$Infection.Status #mouse infection data
Scoc<-liz$Infection.Status  #liz infection data

#rename, make sure they are a character 
Mouse <- as.character(Pema)
Lizard <- as.character(Scoc)



# prepare a summary table with one row per experiment
tickplot<- tibble(
  host=factor(c( rep("Mouse", length(Mouse)), rep("Lizard", length(Lizard)))), 
  outcome=c(Mouse, Lizard)) %>%
  group_by(host) %>%
  summarise(prob=mean(outcome == "Pos"), n=n()) %>%
  mutate(se=sqrt(abs(prob*(1-prob)/n)))


# visualizing with boxplot and 95% confidence intervals
fig_1 <- ggplot(data=tickplot, aes(x=host, y=prob, fill=host)) + 
              coord_cartesian(ylim=c(0,1)) + 
              geom_boxplot(
              stat='identity',
                 aes(ymin=prob-1.96*se, 
                 lower = prob - se,
                 middle = prob,
                 upper = prob + se,
                 ymax = prob + 1.96*se)) + 
      scale_fill_manual(values=c("darkseagreen", "#56B4E9"), 
                          name="Larval Host") + #legend label 
                          theme_bw()  + 
      ylab("Proportion of Nymphs Infected")+
      xlab("Larval Host Bloodmeal") +
      ggtitle("Proportion of Nymphal Infection by Larval Bloodmeal Identity") +
      theme(plot.title = element_text(hjust = 0.5, size = 10))

#change the theme for proper title, axes, and legend sizes 
my_theme = theme(
  plot.title = element_text(size= 13),
  axis.title.x = element_text(size = 12),
  axis.text.x = element_text(size = 11),
  axis.title.y = element_text(size = 12), 
  legend.key.size = unit(1, 'cm'),
  legend.key.height = unit(1, 'cm'),
  legend.key.width = unit(1, 'cm'),
  legend.title = element_text(size = 11),
  legend.text = element_text(size =10))

fig_1 <- fig_1 + my_theme


ggsave("fig_1.pdf", plot = fig_1, height= 15, width = 14, device = "pdf", units = "cm", dpi = 500)


```


```{r}
#lets look at the fig 

fig_1


```








